oidc:
  enabled: true
  authorizationEndpoint: "https://auth.crust.life/application/o/guacamole/authorize/"
  jwksEndpoint: "https://auth.crust.life/application/o/guacamole/jwks/"
  issuer: "https://auth.crust.life/application/o/guacamole/"
  clientId: "guacamole"
  redirectUri: "https://remote.crust.life/guacamole/"
postgresql:
  auth:
    existingSecret: "	guacamole-guacamole-database"